# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 15:47
from __future__ import unicode_literals

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyer_customer_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('objects', users.managers.AuthorManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='buyer',
            managers=[
                ('objects', users.managers.BuyerManager()),
            ],
        ),
    ]
